handle deleted files

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,7 +47,12 @@ jobs:
         if: success()
         run: |
           while read file; do
-            aws s3 cp "$file" "s3://srophe-syriaca-front-end/$file" 
+            echo "Attempting to upload $file..."
+            if ! aws s3 cp "$file" "s3://srophe-syriaca-front-end/$file" ; then
+              echo "File $file not found. Falling back to sync for deletion handling."
+              aws s3 sync ./ s3://srophe-syriaca-front-end --delete --exclude "json-data/*" --include "*"
+              break  # Stop further uploads and rely on sync
+            fi
           done < changed_files.txt
         env:
           AWS_REGION: ${{ secrets.AWS_REGION }}
